name: inbox_memo
description: A new Flutter project.
publish_to: "none"
version: 1.4.2+17

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.1.0
  package_info_plus: ^3.1.2
  flutter_launcher_icons: ^0.11.0
  intl: ^0.18.0
  freezed_annotation: ^2.0.3
  share_plus: ^6.3.2
  url_launcher: ^6.1.9
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6

dev_dependencies:
  freezed:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test:

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/launcher_icon/icon_adaptive_foreground.png"
