name: inbox_memo
description: A new Flutter project.
publish_to: "none"
version: 1.5.3+21

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  shared_preferences: ^2.2.2
  package_info_plus: ^4.2.0
  flutter_launcher_icons: ^0.11.0
  intl: ^0.18.1
  freezed_annotation: ^2.0.3
  share_plus: ^7.2.1
  url_launcher: ^6.2.0
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.4

dev_dependencies:
  freezed:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  test:

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/launcher_icon/icon_adaptive_foreground.png"
